#!/usr/bin/env node
// Проверка архитектуры Feature-Sliced Design (эталон: MelevaTe/hackathon-spring-2026-frontend).
// Плюс: движки анимаций (banned-import, css-animation — ADR-036)
// и стили только из токенов (hardcoded-color, arbitrary-value, spacing-scale, motion-literal, inline-style — ADR-033).
// Использование: node fsd-check.mjs [путь/к/src] [--warn-only]
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, resolve, dirname, sep } from "node:path";

const args = process.argv.slice(2);
const warnOnly = args.includes("--warn-only");
const SRC = resolve(args.find((a) => !a.startsWith("--")) ?? "src");
const LAYERS = ["shared", "entities", "features", "widgets", "pages", "app"]; // снизу вверх
const SLICED = new Set(["entities", "features", "widgets", "pages"]);
const rank = (l) => LAYERS.indexOf(l);

const files = [];
(function walk(d) {
  for (const n of readdirSync(d)) {
    const p = join(d, n);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(ts|tsx|css)$/.test(n) && !/\.d\.ts$/.test(n)) files.push(p);
  }
})(SRC);

// src/<layer>/<slice>/<segment>/...
function locate(absPath) {
  const parts = relative(SRC, absPath).split(sep);
  const layer = parts[0];
  if (!LAYERS.includes(layer)) return { layer: null, parts };
  const slice = SLICED.has(layer) ? parts[1] : null;
  return { layer, slice, parts };
}

const problems = [];
const warnings = [];
const add = (file, line, rule, msg) =>
  problems.push(`${relative(process.cwd(), file)}:${line}  [${rule}] ${msg}`);
const warn = (file, line, rule, msg) =>
  warnings.push(`${relative(process.cwd(), file)}:${line}  [${rule}] ${msg}`);

// 0.1 Стили только из токенов (ADR-033). Источник — shared/config/tokens.ts, тема генерируется gen-tokens.mjs.
const GENERATED = "AUTO-GENERATED by gen-tokens.mjs";
const TOKEN_FILES = /(^|\/)shared\/config\/(tokens|motion)\.ts$/;
let SPACING = [0, 0.5, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16];
try {
  const m = readFileSync(join(SRC, "shared/config/tokens.ts"), "utf8").match(/spacingSteps\s*=\s*\[([^\]]+)\]/);
  if (m) SPACING = m[1].split(",").map(Number).filter((n) => !Number.isNaN(n));
} catch {}
const STYLE_RULES = [
  ["hardcoded-color", /(?:^|["'`\s(:,{])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})(?![\w-])|\b(?:rgba?|hsla?|oklch|oklab|lab|lch|hwb)\(\s*[\d.]/,
    "цвет литералом — возьмите семантический токен (bg-primary, text-muted-foreground, cssVar('chart-1'))"],
  ["arbitrary-value", /(?<![\w-])-?[a-z][a-z0-9]*(?:-[a-z0-9]+)*-\[(?!var\(|--)[^\]\s"'`]+\](?!:)/,
    "произвольное значение Tailwind (p-[13px], text-[#fff], w-[420px]) — добавьте токен в tokens.ts или используйте шкалу"],
  ["motion-literal", /\b(?:duration|delay|stiffness|damping|mass|bounce|visualDuration|staggerChildren|delayChildren|repeatDelay)\s*:\s*(?!0\b)\d|\bease\s*:\s*\[|(?<![\w-])(?:duration|delay)-\d+(?![\w-])/,
    "число в анимации — используйте tween/spring/duration из @/shared/config/motion или классы duration-fast|base|slow"],
  ["inline-style", /style=\{\{[^}]*\b(?:padding|margin|gap|fontSize|lineHeight|borderRadius|letterSpacing|fontWeight|zIndex)\w*\s*:\s*["'`]?-?\d/,
    "размер в inline-style — используйте классы шкалы (p-4, text-sm, rounded-lg, z-modal)"],
];
const SPACING_RE = /(?<![\w-])-?(?:p|px|py|pt|pr|pb|pl|ps|pe|m|mx|my|mt|mr|mb|ml|ms|me|gap|gap-x|gap-y|space-x|space-y|inset|inset-x|inset-y|top|right|bottom|left|start|end)-(\d+(?:\.\d+)?)(?![\w.%\/-])/g;

// 0. Движки анимаций (ADR-036): motion/react — основной; three/R3F/ogl/gsap/lenis — разрешены; дубли — нет
const BANNED = [
  [/^framer-motion(\/.*)?$/, "импортируйте из \"motion/react\" (пакет motion), а не из framer-motion (ADR-036)"],
  [/^(react-spring|@react-spring\/.*)$/, "react-spring дублирует motion — используйте motion/react (ADR-036)"],
  [/^(animejs|popmotion)$/, "дублирующий движок анимаций — используйте motion/react или gsap (ADR-036)"],
  [/^(tw-animate-css|tailwindcss-animate)$/, "CSS-анимации Tailwind выключены в теме — анимируйте через motion/react (ADR-036)"],
];
const CSS_ANIM_RE = /@keyframes\s|(?<![\w-])(?:[\w-]+:)*animate-(?:spin|ping|pulse|bounce|in|out|\[)/;
const IMPORT_RE = /(?:import|export)\s[^"']*?from\s*["']([^"']+)["']|import\(\s*["']([^"']+)["']\s*\)|^\s*import\s*["']([^"']+)["']|@import\s+["']([^"']+)["']/g;

for (const file of files) {
  const src = readFileSync(file, "utf8");
  const me = locate(file);
  if (!me.layer) continue;
  const lines = src.split("\n");
  const rel = relative(SRC, file).split(sep).join("/");
  const styleCheck = !TOKEN_FILES.test(rel) && !src.includes(GENERATED) && !/\.(test|spec|stories)\.tsx?$/.test(rel);
  const vendorUi = rel.startsWith("shared/ui/"); // код shadcn/реестров: стиль-нарушения — предупреждения, F2 чистит при адаптации
  lines.forEach((text, i) => {
    if (styleCheck && !/^\s*(\/\/|\*|\/\*)/.test(text)) {
      const report = vendorUi ? warn : add;
      for (const [rule, re, msg] of STYLE_RULES) if (re.test(text)) report(file, i + 1, rule, msg);
      for (const m of text.matchAll(SPACING_RE))
        if (!SPACING.includes(Number(m[1])))
          report(file, i + 1, "spacing-scale", `"${m[0].trim()}" вне сетки — разрешены шаги ${SPACING.join(", ")} (tokens.ts → spacingSteps)`);
    }
    if (CSS_ANIM_RE.test(text))
      (vendorUi ? warn : add)(file, i + 1, "css-animation", "CSS-анимация (@keyframes / animate-*) — в своём коде только motion/react (ADR-036)");
    for (const m of text.matchAll(IMPORT_RE)) {
      const spec = m[1] ?? m[2] ?? m[3] ?? m[4];
      let targetAbs;
      const viaAlias = spec.startsWith("@/");
      if (viaAlias) targetAbs = join(SRC, spec.slice(2));
      else if (spec.startsWith(".")) targetAbs = resolve(dirname(file), spec);
      else {
        for (const [re, msg] of BANNED) if (re.test(spec)) add(file, i + 1, "banned-import", `"${spec}": ${msg}`);
        continue; // npm-пакет
      }
      const t = locate(targetAbs);
      if (!t.layer) continue;
      const ln = i + 1;
      const sameSlice = me.layer === t.layer && (me.slice === t.slice || !SLICED.has(me.layer));

      // 1. Направление зависимостей: только вниз
      if (rank(t.layer) > rank(me.layer))
        add(file, ln, "layer-direction", `${me.layer} не может импортировать ${t.layer} ("${spec}")`);

      // 2. Слайсы одного слоя не знают друг о друге
      if (SLICED.has(me.layer) && me.layer === t.layer && me.slice !== t.slice)
        add(file, ln, "cross-slice", `${me.layer}/${me.slice} импортирует соседний ${t.layer}/${t.slice} — поднимите композицию на слой выше`);

      // 3. Чужой слайс — только через публичный API (index.ts)
      if (SLICED.has(t.layer) && !sameSlice) {
        const depth = t.parts.length - 2; // всё после layer/slice
        const isIndex = depth <= 0 || (depth === 1 && /^index(\.tsx?)?$/.test(t.parts[2]));
        if (!isIndex) add(file, ln, "public-api", `глубокий импорт "${spec}" — импортируйте из "@/${t.layer}/${t.slice}"`);
      }

      // 4. Внутри своего слайса — относительные пути
      if (viaAlias && sameSlice && SLICED.has(me.layer))
        add(file, ln, "relative-inside-slice", `внутри ${me.layer}/${me.slice} используйте относительный импорт вместо "${spec}"`);
    }
  });
}

// 5. У каждого слайса есть index.ts
for (const layer of SLICED) {
  let slices = [];
  try { slices = readdirSync(join(SRC, layer)); } catch { continue; }
  for (const s of slices) {
    const dir = join(SRC, layer, s);
    if (!statSync(dir).isDirectory()) continue;
    const has = readdirSync(dir).some((n) => /^index\.tsx?$/.test(n));
    if (!has) add(dir, 0, "no-public-api", `у слайса ${layer}/${s} нет index.ts`);
  }
}

if (warnings.length) console.log(warnings.map((w) => "⚠ " + w).join("\n") + `\n⚠ fsd-check: ${warnings.length} предупреждений (shared/ui)\n`);
if (problems.length === 0) {
  console.log(`✔ fsd-check: ${files.length} файлов, нарушений нет`);
  process.exit(0);
}
console.log(problems.join("\n"));
console.log(`\n${warnOnly ? "⚠" : "✖"} fsd-check: ${problems.length} нарушений в ${files.length} файлах`);
process.exit(warnOnly ? 0 : 1);
