#!/usr/bin/env node
// Генератор темы из единого источника токенов (ADR-033).
//   node --experimental-strip-types gen-tokens.mjs <tokens.ts> --css <theme.css> [--md <DESIGN.md>] [--check]
// --css    Tailwind 4 (@theme) + shadcn-переменные (:root/.dark) + утилиты
// --md     заменяет блок между <!-- tokens:begin --> и <!-- tokens:end --> таблицами токенов
// --check  ничего не пишет, exit 1 если файлы устарели (для verify.sh / CI)
// Также проверяет контраст пар x / x-foreground (WCAG 2.x, ≥ 4.5:1) с учётом contrastLargeTextOnly.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, relative } from "node:path";
import { pathToFileURL } from "node:url";

const args = process.argv.slice(2);
const opt = (k) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : undefined; };
const src = args.find((a, i) => !a.startsWith("--") && !["--css", "--md"].includes(args[i - 1]));
const cssOut = opt("--css"), mdOut = opt("--md"), check = args.includes("--check");
if (!src || (!cssOut && !mdOut)) {
  console.error("использование: gen-tokens.mjs <tokens.ts> --css <theme.css> [--md <DESIGN.md>] [--check]");
  process.exit(2);
}
let t;
try { t = await import(pathToFileURL(resolve(src)).href); }
catch (e) {
  if (e.code === "ERR_UNKNOWN_FILE_EXTENSION")
    console.error("✖ запусти с флагом: node --experimental-strip-types … (Node ≥ 22.6)");
  else console.error(e);
  process.exit(2);
}

const px = (n) => (n === 0 ? "0" : `${n}px`);
const ms = (s) => `${Math.round(s * 1000)}ms`;
const bez = (a) => `cubic-bezier(${a.join(", ")})`;
const kebab = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
const block = (sel, lines, ind = "  ") => `${sel} {\n${lines.map((l) => ind + l).join("\n")}\n}\n`;
const flat = (obj, pre = "") => Object.entries(obj).flatMap(([k, v]) =>
  typeof v === "object" ? flat(v, `${pre}${k}-`) : [[`${pre}${k}`, v]]);

// --- контраст ---------------------------------------------------------------
const lum = (hex) => {
  const n = hex.replace("#", ""); if (!/^[0-9a-f]{6}$/i.test(n)) return null;
  const c = [0, 2, 4].map((i) => parseInt(n.slice(i, i + 2), 16) / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => { const x = lum(a), y = lum(b); if (x == null || y == null) return null;
  return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05); };
const pairs = [];
let contrastFail = 0;
for (const mode of ["light", "dark"]) {
  const s = t.semantic[mode];
  for (const k of Object.keys(s)) {
    const fg = s[`${k}-foreground`]; if (!fg) continue;
    const r = ratio(s[k], fg); if (r == null) continue;
    const large = k in (t.contrastLargeTextOnly ?? {});
    const ok = r >= 4.5 || (large && r >= 3);
    if (!ok) { contrastFail++; console.error(`✖ контраст ${mode}: ${k} / ${k}-foreground = ${r.toFixed(2)}:1 < 4.5`); }
    pairs.push({ mode, k, r, large });
  }
}

// --- CSS --------------------------------------------------------------------
const HEADER = "/* AUTO-GENERATED by gen-tokens.mjs from tokens.ts — НЕ ПРАВИТЬ РУКАМИ (ADR-033). */";
function css() {
  const L = t.semantic.light, D = t.semantic.dark;
  const rootVars = [
    ...Object.entries(L).map(([k, v]) => `--${k}: ${v};`),
    ...Object.entries(t.gradient).map(([k, v]) => `--gradient-${k}: ${v};`),
    ...Object.entries(t.shadow.light).map(([k, v]) => `--elev-${k}: ${v};`),
    `--radius: ${px(t.radius.md)}; /* для shadcn-компонентов, которые считают от --radius */`,
  ];
  const darkVars = [
    ...Object.entries(D).map(([k, v]) => `--${k}: ${v};`),
    ...Object.entries(t.shadow.dark).map(([k, v]) => `--elev-${k}: ${v};`),
    // градиенты с вариантом «-dark» подменяются в тёмной теме
    ...Object.keys(t.gradient).filter((k) => `${k}-dark` in t.gradient).map((k) => `--gradient-${k}: var(--gradient-${k}-dark);`),
  ];
  const theme = [
    "/* дефолтные шкалы Tailwind выключены: доступны только токены ниже */",
    "--color-*: initial;", "--text-*: initial;", "--radius-*: initial;", "--shadow-*: initial;",
    "--ease-*: initial;", "--animate-*: initial; /* CSS-анимации запрещены (ADR-031), только motion/react */",
    `--font-sans: ${t.font.sans};`, `--font-display: ${t.font.display};`, `--font-mono: ${t.font.mono};`,
    ...Object.entries(t.fontWeight).map(([k, v]) => `--font-weight-${k}: ${v};`),
    `--spacing: ${px(t.spacingBase)};`,
    ...Object.entries(t.control).map(([k, v]) => `--spacing-control-${k}: ${px(v)};`),
    ...Object.entries(t.text).flatMap(([k, v]) => [`--text-${k}: ${px(v.size)};`, `--text-${k}--line-height: ${px(v.lineHeight)};`]),
    ...Object.entries(t.radius).map(([k, v]) => `--radius-${k}: ${px(v)};`),
    "--radius-full: 9999px;",
    ...Object.entries(t.motion.ease).map(([k, v]) => `--ease-${kebab(k)}: ${bez(v)};`),
    `--default-transition-duration: ${ms(t.motion.duration.fast)};`,
    `--default-transition-timing-function: ${bez(t.motion.ease.out)};`,
    `--color-white: ${t.palette.white};`, `--color-black: ${t.palette.black};`,
    ...Object.entries(t.palette.sber).map(([k, v]) => `--color-sber-${k}: ${v};`),
    "--tracking-display: -0.03em;", "--tracking-hero: -0.055em;", "--tracking-caps: 0.06em;",
  ];
  const inline = [
    ...Object.keys(L).map((k) => `--color-${k}: var(--${k});`),
    ...Object.keys(t.shadow.light).map((k) => `--shadow-${k}: var(--elev-${k});`),
  ];
  const utils = [
    ...Object.entries(t.motion.duration).map(([k, v]) => `@utility duration-${k} {\n  transition-duration: ${ms(v)};\n}`),
    ...Object.entries(t.zIndex).map(([k, v]) => `@utility z-${k} {\n  z-index: ${v};\n}`),
    "@utility pt-safe {\n  padding-top: env(safe-area-inset-top);\n}",
    "@utility pb-safe {\n  padding-bottom: env(safe-area-inset-bottom);\n}",
    "@utility bg-brand-gradient {\n  background-image: var(--gradient-brand);\n}",
    "@utility bg-glow {\n  background-image: var(--gradient-glow);\n}",
    ...["brand-deep", "brand-conic", "sheen", "track"].map((k) => `@utility bg-${k} {\n  background-image: var(--gradient-${k});\n}`),
    "/* фон страниц: мятный градиент Сбера, не уезжает при прокрутке */\n@utility bg-page {\n  background-color: var(--background);\n  background-image: var(--gradient-page);\n  background-attachment: fixed;\n}",
    "@utility text-brand-gradient {\n  background-image: var(--gradient-brand);\n  background-clip: text;\n  color: transparent;\n}",
    "/* шторка: не выше экрана с учётом выреза */\n@utility max-h-sheet {\n  max-height: calc(100dvh - 16px - env(safe-area-inset-top));\n}",
    "/* место под нижнюю навигацию телефона */\n@utility pb-nav {\n  padding-bottom: calc(96px + env(safe-area-inset-bottom));\n}",
    "/* чат помощника на всю доступную высоту */\n@utility h-chat {\n  height: calc(100dvh - 248px - env(safe-area-inset-bottom));\n  min-height: 420px;\n  @media (width >= 64rem) {\n    height: calc(100dvh - 216px);\n  }\n}",
    "@utility scrollbar-none {\n  scrollbar-width: none;\n  &::-webkit-scrollbar {\n    display: none;\n  }\n}",
  ];
  return [
    HEADER,
    ...t.fontImports.map((u) => `@import url("${u}");`),
    '@import "tailwindcss";', "",
    "@custom-variant dark (&:is(.dark *));", "",
    block(":root", rootVars), block(".dark", darkVars),
    block("@theme", theme), block("@theme inline", inline),
    utils.join("\n\n"), "",
    `@layer base {
  * { @apply border-border outline-ring/50; }
  /* фон html = фон темы: никаких чёрных полос под вырезом и при оттягивании страницы */
  html { -webkit-tap-highlight-color: transparent; background-color: var(--background); }
  /* органичные скругления: суперэллипс вместо дуги окружности (Chrome 139+, остальные — обычный радиус) */
  @supports (corner-shape: ${t.cornerShape ?? "squircle"}) {
    [class*="rounded-"]:not(.rounded-full) { corner-shape: ${t.cornerShape ?? "squircle"}; }
  }
  body {
    @apply bg-page text-foreground font-sans text-sm antialiased;
    font-feature-settings: "tnum" 1; /* табличные цифры: время, счётчики, табель */
  }
  h1, h2, h3 { @apply font-display font-semibold; letter-spacing: -0.03em; }
  input, select, textarea, button { font: inherit; }
  ::selection { background: var(--success-soft); color: var(--success-soft-foreground); }
  * { scrollbar-width: thin; scrollbar-color: var(--border-strong) transparent; }
  @media (prefers-reduced-motion: reduce) {
    *, ::before, ::after { transition-duration: 0ms !important; scroll-behavior: auto !important; }
  }
}
`,
  ].join("\n");
}

// --- Markdown ---------------------------------------------------------------
function md() {
  const L = t.semantic.light, D = t.semantic.dark;
  const c = (v) => (String(v).startsWith("#") ? `\`${v}\`` : `\`${v}\``);
  const contrast = (mode, k) => { const p = pairs.find((x) => x.mode === mode && x.k === k);
    return p ? `${p.r.toFixed(2)}${p.large && p.r < 4.5 ? " (только крупный)" : ""}` : ""; };
  const out = [];
  out.push("<!-- Сгенерировано gen-tokens.mjs из tokens.ts. Правь tokens.ts и запускай `npm run gen:tokens`. -->", "");
  out.push("#### Семантические цвета", "", "| Токен | Класс | Светлая | Тёмная | Контраст с -foreground (свет / тём.) |", "|---|---|---|---|---|");
  for (const k of Object.keys(L)) {
    if (k.endsWith("-foreground")) continue;
    out.push(`| \`${k}\` | \`bg-${k}\` / \`text-${k}\` | ${c(L[k])} | ${c(D[k])} | ${[contrast("light", k), contrast("dark", k)].filter(Boolean).join(" / ")} |`);
  }
  out.push("", "Пары `x-foreground` — цвет текста/иконок на фоне `x`. Исключения по контрасту (только крупный текст):", "");
  for (const [k, why] of Object.entries(t.contrastLargeTextOnly)) out.push(`- \`${k}\` — ${why}`);
  out.push("", "#### Шкалы (только для токенов, не в className)", "", "| Шкала | Значения |", "|---|---|");
  for (const [k, v] of Object.entries(t.palette)) {
    if (typeof v === "string") out.push(`| ${k} | \`${v}\` |`);
    else out.push(`| ${k} | ${Object.entries(v).map(([s, h]) => `${s} \`${h}\``).join(", ")} |`);
  }
  out.push("", "#### Типографика (шкала Nova; дефолтные размеры Tailwind выключены)", "", "| Класс | Размер / интерлиньяж | Для чего |", "|---|---|---|");
  for (const [k, v] of Object.entries(t.text)) out.push(`| \`text-${k}\` | ${v.size} / ${v.lineHeight} px | ${v.role} |`);
  out.push("", `Шрифты: \`font-sans\` — SB Sans Text (весь UI), \`font-display\` — SB Sans Display (h1–h3, KPI, вердикт). Начертания: ${Object.entries(t.fontWeight).map(([k, v]) => `\`font-${k}\` ${v}`).join(", ")}.`);
  out.push("", "#### Отступы, контролы, радиусы, тени, слои", "");
  out.push(`- Сетка ${t.spacingBase} px. Для \`p-* m-* gap-* space-* inset-*\` разрешены шаги: ${t.spacingSteps.map((s) => `\`${s}\` (${s * t.spacingBase} px)`).join(", ")}.`);
  out.push(`- Высота контролов: ${Object.entries(t.control).map(([k, v]) => `\`h-control-${k}\` ${v}`).join(", ")} px.`);
  out.push(`- Радиусы: ${Object.entries(t.radius).map(([k, v]) => `\`rounded-${k}\` ${v}`).join(", ")} px, \`rounded-full\`.`);
  out.push(`- Тени: ${Object.keys(t.shadow.light).map((k) => `\`shadow-${k}\``).join(", ")} (свои значения в тёмной теме).`);
  out.push("- Safe-area телефона: `pt-safe`, `pb-safe`.");
  out.push(`- Слои: ${Object.entries(t.zIndex).map(([k, v]) => `\`z-${k}\` ${v}`).join(", ")}.`);
  out.push("", "#### Движение (motion/react через `@/shared/config/motion`; CSS-переходы — классами)", "", "| Токен | Значение | CSS-класс |", "|---|---|---|");
  for (const [k, v] of Object.entries(t.motion.duration)) out.push(`| duration.${k} | ${v} с | \`duration-${k}\` |`);
  for (const [k, v] of Object.entries(t.motion.ease)) out.push(`| ease.${k} | \`${bez(v)}\` | \`ease-${kebab(k)}\` |`);
  for (const [k, v] of Object.entries(t.motion.spring)) out.push(`| spring.${k} | ${Object.entries(v).filter(([a]) => a !== "type").map(([a, b]) => `${a} ${b}`).join(", ")} | — |`);
  out.push(`| swipe | ${flat(t.motion.swipe).map(([a, b]) => `${a} ${b}`).join(", ")} | — |`);
  out.push(`| toast | ${flat(t.motion.toast).map(([a, b]) => `${a} ${b}`).join(", ")} | — |`);
  out.push(`| kiosk | ${flat(t.motion.kiosk).map(([a, b]) => `${a} ${b}`).join(", ")} | — |`);
  return out.join("\n");
}

// --- запись / проверка ------------------------------------------------------
let stale = 0;
function emit(file, content) {
  const cur = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (cur === content) return;
  if (check) { stale++; console.error(`✖ ${relative(process.cwd(), file)} устарел — запусти npm run gen:tokens`); }
  else { writeFileSync(file, content); console.log(`✔ записан ${relative(process.cwd(), file)}`); }
}
if (cssOut) emit(resolve(cssOut), css());
if (mdOut) {
  const file = resolve(mdOut);
  const cur = readFileSync(file, "utf8");
  const re = /(<!-- tokens:begin -->)[\s\S]*?(<!-- tokens:end -->)/;
  if (!re.test(cur)) { console.error(`✖ в ${mdOut} нет маркеров <!-- tokens:begin --> … <!-- tokens:end -->`); process.exit(2); }
  emit(file, cur.replace(re, `$1\n${md()}\n$2`));
}
if (contrastFail || stale) process.exit(1);
console.log(`✔ gen-tokens: ${check ? "актуально" : "готово"}, контраст ок (${pairs.length} пар)`);
