export * from "./types";
export { useDb, getDb } from "./mock/store";
export { REASONS, SYSTEM_CODES } from "./mock/reasons";
export { DEMO_INVITES } from "./mock/seed";
export * from "./mock/derived";
export * as api from "./mock/server";
export type { ScanResult, WorkerDraft } from "./mock/server";
export { terminalModeOf, KIOSK_ONLINE_MS, FACE_FIRST_MARGIN } from "./mock/server";
export * as assistant from "./mock/assistant";
export type { AssistantAnswer, AssistantTable, LlmConfig } from "./mock/assistant";
